export const DAFTAR_KANTAH = [
  'Kantah Kota Administrasi Jakarta Pusat',
  'Kantah Kota Administrasi Jakarta Utara',
  'Kantah Kota Administrasi Jakarta Barat',
  'Kantah Kota Administrasi Jakarta Selatan',
  'Kantah Kota Administrasi Jakarta Timur',
  'Kantah Kabupaten Administrasi Kepulauan Seribu',
  'Kantah Kota Bogor',
  'Kantah Kabupaten Bogor',
  'Kantah Kota Depok',
  'Kantah Kota Bekasi',
  'Kantah Kabupaten Bekasi',
  'Kantah Kota Tangerang',
  'Kantah Kota Tangerang Selatan',
  'Kantah Kabupaten Tangerang',
  'Kantah Kota Bandung',
  'Kantah Kabupaten Bandung',
  'Kantah Kabupaten Bandung Barat',
  'Kantah Kota Cimahi',
  'Kantah Kota Cirebon',
  'Kantah Kabupaten Cirebon',
  'Kantah Kabupaten Garut',
  'Kantah Kabupaten Sukabumi',
  'Kantah Kota Sukabumi',
  'Kantah Kabupaten Cianjur',
  'Kantah Kabupaten Tasikmalaya',
  'Kantah Kota Tasikmalaya',
  'Kantah Kabupaten Ciamis',
  'Kantah Kota Banjar',
  'Kantah Kabupaten Kuningan',
  'Kantah Kabupaten Majalengka',
  'Kantah Kabupaten Sumedang',
  'Kantah Kabupaten Indramayu',
  'Kantah Kabupaten Subang',
  'Kantah Kabupaten Purwakarta',
  'Kantah Kabupaten Karawang',
  'Kantah Kabupaten Pangandaran',
  'Kantah Kota Semarang',
  'Kantah Kabupaten Semarang',
  'Kantah Kota Surakarta',
  'Kantah Kota Yogyakarta',
  'Kantah Kabupaten Sleman',
  'Kantah Kabupaten Bantul',
  'Kantah Kabupaten Kulon Progo',
  'Kantah Kabupaten Gunungkidul',
  'Kantah Kota Surabaya',
  'Kantah Kabupaten Sidoarjo',
  'Kantah Kabupaten Gresik',
  'Kantah Kota Malang',
  'Kantah Kabupaten Malang',
  'Kantah Kota Batu',
  'Kantah Kota Medan',
  'Kantah Kabupaten Deli Serdang',
  'Kantah Kota Makassar',
  'Kantah Kota Denpasar',
  'Kantah Kabupaten Badung',
  'Kantah Kota Balikpapan',
  'Kantah Kota Samarinda',
  'Kantah Kota Banjarmasin',
  'Kantah Kota Palembang',
  'Kantah Kota Pekanbaru',
  'Kantah Kota Padang',
  'Kantah Kota Batam',
  'Kantah Kota Pontianak',
  'Kantah Kota Manado',
  'Kantah Kota Ambon',
  'Kantah Kota Jayapura',
].sort()
